//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryAmount
    {
        public int EntryID { get; set; }
        public int AccountID { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Entry Entry { get; set; }
        public virtual Account Account { get; set; }
    }
}
