//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class Percentage
    {
        public int AccountID { get; set; }
        public int CategoryID { get; set; }
        public decimal Percent { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Category Category { get; set; }
    }
}
